spring:
  application:
    name: QUIZE-SERVICES
  data:
    mongodb:
      uri: mongodb://localhost:27017/MS_quiz_Services
server:
  port: 9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: QUIZE-SERVICES-${spring.application.instance_id:${random.value}}

# for automatic refresh actuator on property
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # rabbitMQ related config
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
